#+TITLE: tree-sitter layer
#+TAGS: layer|misc|general


# TOC links should be GitHub style anchors.
* Table of Contents                                        :TOC_4_gh:noexport:
- [[#description][Description]]
  - [[#features][Features:]]
- [[#install][Install]]
- [[#configure][Configure]]

* Description
This layer integrates
[[https://github.com/emacs-tree-sitter/elisp-tree-sitter][=Emacs Tree-sitter=]]
and a few packages built around it. An Emacs build supporting dynamic modules is
required.

Language (i.e. major-mode) support is somewhat limited and varies by feature.
Refer to the README/documentation of the package providing the feature for
specifics.

** Features:
  - Syntax highlighting
  - Indentation (experimental)
  - Folding (experimental)

* Install
To use this configuration layer, add it to your =~/.spacemacs=. You will need to
add =tree-sitter= to the existing =dotspacemacs-configuration-layers= list in
this file.

* Configure
  #+begin_comment
  Enabled features should override existing mechanism seamlessly. For example,
  there's no need to separately disable regexp-based syntax highlighting, and in
  general you do not need to update keybindings to point to tree sitter
  analogues.
  #+end_comment
  
Set =tree-sitter-syntax-highlight-enable t= for syntax highlighting, provided by
=tree-sitter-hl-mode= which is bundled with
[[https://github.com/emacs-tree-sitter/elisp-tree-sitter][tree-sitter-mode]].
Default: =t=.

Set =tree-sitter-indent-enable t= for code indentation, provided by
[[https://codeberg.org/FelipeLema/tree-sitter-indent.el][=tree-sitter-indent=]].
Default: =nil=

Set =tree-sitter-fold-enable t= for code folding, provided by
[[https://github.com/jcs090218/ts-fold][=ts-fold=]]. Default: =nil=
