#!/bin/zsh

set -eu

cd "$HOME"

# --- GENERAL -----------------------------------------------------------------
echo "Initializing submodules..."
yadm submodule update --recursive --init
if [ $(uname) = "Linux" ]; then
    dconf load / < "$HOME/.config/dconf.ini"
fi

# --- EMACS -------------------------------------------------------------------
touch "$HOME/.emacs-custom.el"

# --- ZSH ---------------------------------------------------------------------
sh -c "KEEP_ZSHRC=yes RUNZSH=no $(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
ZSH_CUSTOM="$ZSH/custom"  # not defined yet because oh-my-zsh hasn't run
git clone https://github.com/denysdovhan/spaceship-prompt.git "$ZSH/CUSTOM/themes/spaceship-prompt"
ln -s "$ZSH_CUSTOM/themes/spaceship-prompt/spaceship.zsh-theme" "$ZSH_CUSTOM/themes/spaceship.zsh-theme"
exec zsh -l
